In [3]:
import numpy as np
arr=np.array([[2,3,4],[5,6,8]])
arr.shape

(2, 3)

In [5]:
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [8]:
arr2 = np.array(range(10,170,10))
arr2 = arr2.reshape(4,4)
print(arr2)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]


In [14]:
arr1 = np.array(range(0,16,1))
arr1 = arr1.reshape(4,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [15]:
print(arr1+arr2)


[[ 10  21  32  43]
 [ 54  65  76  87]
 [ 98 109 120 131]
 [142 153 164 175]]


In [16]:
print(arr1*arr2)

[[   0   20   60  120]
 [ 200  300  420  560]
 [ 720  900 1100 1320]
 [1560 1820 2100 2400]]


In [17]:
print(arr1/arr2)

[[0.         0.05       0.06666667 0.075     ]
 [0.08       0.08333333 0.08571429 0.0875    ]
 [0.08888889 0.09       0.09090909 0.09166667]
 [0.09230769 0.09285714 0.09333333 0.09375   ]]


In [18]:
print(arr1-arr2)

[[ -10  -19  -28  -37]
 [ -46  -55  -64  -73]
 [ -82  -91 -100 -109]
 [-118 -127 -136 -145]]


In [20]:
arr.T

array([[2, 5],
       [3, 6],
       [4, 8]])

In [21]:
arr2.T

array([[ 10,  50,  90, 130],
       [ 20,  60, 100, 140],
       [ 30,  70, 110, 150],
       [ 40,  80, 120, 160]])

In [22]:
print(arr2)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
